project:
   name: Icepack Example 03
verbosity: null
files:
   skip:
       - "doc"
       - ".pyccoon.yaml"
       - "build"
       - "\\.git*"
       - ".+\\.pyc"
       - "CMakeLists.txt"
       - "Makefile"
       - "data.hpp"
       - "data.cpp"
   copy:
       - "pyccoon.svg"
       - ".+\\css"
       - "\\.pyccoon.yaml"
documentation:
   mathjax: true
   linebreaking-behavior: normal
   css-path: null
   custom-html-template: null

